### ISSUE TITLE
LaTeX not rendering in docs

### ISSUE THREAD

**Issue by oscarhiggott** [QEC-pages/QDistRnd#14]
From https://github.com/openjournals/joss-reviews/issues/4120

The LaTeX in the docs doesn't currently render, which is most noticeable in Chapter 3: https://qec-pages.github.io/QDistRnd/doc/chap3.html. It's not important (only worth changing if it's an easy fix) but it would be much easier to read if it did render.

E.g. here:
https://github.com/QEC-pages/QDistRnd/blob/2b8b6da8c3311baf6cb697db8f2b2b46f6a231ce/doc/body.autodoc#L352-L354

**Comment by LeonidPryadko** [comment]
The equations require that MathJax be on.  For some reason, it is off by default, but can be enabled by clicking "MathJax on" link near the top of the page (at least this is how it works on Firefox).  Alternatively, there is also a pdf version of the manual at https://github.com/QEC-pages/QDistRnd/releases.

**Comment by oscarhiggott** [comment]
Ah sorry I didn't notice the "MathJax on" button! It might be worth linking to the url with MathJax on by default in https://qec-pages.github.io/QDistRnd/ (e.g. https://qec-pages.github.io/QDistRnd/doc/chap0_mj.html instead of https://qec-pages.github.io/QDistRnd/doc/chap0.html) as I imagine most users would prefer that, but closing this issue now
