### ISSUE TITLE
Pair not specified in MTXE format

### ISSUE THREAD

**Issue by oscarhiggott** [QEC-pages/QDistRnd#17]
From https://github.com/openjournals/joss-reviews/issues/4120

I noticed that the `pair` variable is not recorded in the MTXE file format (unless the user chooses to add it in a comment). The required `type` variable stored in the file does not distinguish between pair values of 0, 1 or 2. It therefore seems to me that a user could easily store a file with `pair=1`, for example, and then accidentally use `ReadMTXE` to load it with `pair=2`, leading to incorrectly permuted columns.

Is there a good reason why you do not want `pair` to be explicitly specified in the MTXE format, such that `ReadMTXE` can by default use the correct settings when loading?

**Comment by oscarhiggott** [comment]
I notice that pair=2 isn't supported, but perhaps pair = 0 could still be mistakenly interpreted as pair = 1 or vice versa?

**Comment by oscarhiggott** [comment]
To be more concrete, I suppose it would be nice if the `WriteMTXE` function added a comment line by default after the "Field" line, specifying the pair. E.g.:

```
%%MatrixMarket matrix coordinate integer general
% Field: GF(2)
% Pair: 0
```

And then if the `% Pair: 0` line was automatically used (if present) when using `ReadMTXE`. But perhaps there is a reason why you do not want to add this.

**Comment by LeonidPryadko** [comment]
Thanks very much for this and other thoughtful comments.
The main reason for not using the pair field is to simplify the format as
much as possible.
To avoid confusion, the best way is to store CSS matrices with pair=0, and
for non-CSS codes to use the complex format;
This should be the default when exchanging matrices with others.
I will add a note to this end on the page describing the format.  -- Leonid

**Comment by oscarhiggott** [comment]
Great thanks, that makes sense, and a note about this on the page would indeed be helpful

**Comment by LeonidPryadko** [comment]
Documentation updated, should be no confusion now.
