### ISSUE TITLE
TeX / formatting issues in the manual

### ISSUE THREAD

**Issue by fingolfin** [QEC-pages/QDistRnd#25]
E.g. looking at chap5_mj.html I see this:
<img width="1195" alt="Screen Shot 2023-11-17 at 10 51 03" src="https://github.com/QEC-pages/QDistRnd/assets/241512/6425b149-392c-4977-acbb-3e5fcbea6803">

The red parts are rendered like that by MathJax to indicate an issue with the LaTeX code -- indeed there is no macro `\gf` in MathJax. You do declare such a macro for use when TeXing the manual, but that doesn't help for the HTML version.

One simple fix would be to just expand the few uses of that macro to `\mathop{\rm GF}`. There might be better solutions, I don't know.

**Comment by LeonidPryadko** [comment]
Fixed.
