### ISSUE TITLE
Avoid `EvalString`, it is unsecure and difficult to debug issues with it

### ISSUE THREAD

**Issue by fingolfin** [QEC-pages/QDistRnd#26]
At the very least, encapsulate the relevant code into dedicated helpers with a clear comment explaining what the supposed format it: as far as I understand, in the first case, the input is supposed to be a string of either the form `GF(q)` where `q` is a sequence of decimal digits representing a prime power, or else `GF(p^m)` where `p` and `m` are decimal numbers representing a prime resp. a positive integer.

If this was in a dedicated function which clearly states what its input/output, it would be fairly easy for someone to replace it with something better. (Writing a function parsing this without the use of `EvalString` shouldn't be too hard.)

The second instance seems to be there to parse univariate polynomials in a variable `x`. Again, if this was a in a function of its own, it could eventually be replaced.

The latter code also messes around with a global variable `x`, which it "backs up" if present, then uses to make the `EvalString` work -- but this is dangerous: What if there is an error in the data file, and we are interrupted -- the user's global variable `x` now won't be restored? And in HPC-GAP with multiple threads, this has obvious issues if two threads try to load data.

A first step to improve this could be to still use `EvalString`, but without using a global variable, by cleverly using a function expressions. Something in the vein of this:
```gap
BindGlobal("QDR_ParsePoly", function(F, str)
  local func;
  func := EvalString(Concatenation("""
         function(F)
             local x;
             x := Indeterminate(F,"x");
             return """, str, """;
         end
         """));
  return func(F);
end);
```
That still parses arbitrary user input in an unsafe fashion, but at least it doesn't need to deal with global variables.

**Comment by LeonidPryadko** [comment]
Done.  For additional security, I also added a check for allowed characters in the polynomial string, which are digits, 'x', '*', '+', and '-'.  (Notice that a polynomial with integer coefficients is expected).
