### ISSUE TITLE
Move `lib/cyclic.g` and `lib/examples.g` into a different directory? Rename `tmp` dir?

### ISSUE THREAD

**Issue by fingolfin** [QEC-pages/QDistRnd#28]
For a GAP package, normally `lib` contains files that are loaded with the package, and I was confused when looking at the code of this package about these files at first, until I realized they are not being loaded.

I would suggest moving them into a separate directory, e.g. "examples".

Likewise I would suggest to rename or remove the `tmp` directory.

**Comment by LeonidPryadko** [comment]
Done.
