### ISSUE TITLE
References to arXiv

### ISSUE THREAD

**Issue by pan-pavel** [QEC-pages/QDistRnd#3]
In the references, the links to some of the papers are not up-to-date. 
For example, the following references are already published:

1) Breuckmann, Nikolas P., & Eberhardt, J. N. (2020). Balanced product quantum codes. ...
2) Panteleev, P., & Kalachev, G. (2020). Quantum LDPC codes with almost linear minimum
distance ...
3) Hastings, M. B., Haah, J., & O’Donnell, R. (2020). Fiber bundle codes: Breaking the ...

It is better to check all the cited arXiv references and replace them with the links to the published versions.

**Comment by danielskatz** [comment]
from openjournals/joss-reviews#4120

**Comment by LeonidPryadko** [comment]
Fixed: Checked all arXiv references and fixed 4.
