### ISSUE TITLE
Make the parser strict and change `Print` calls to `Error`

### ISSUE THREAD

**Issue by fingolfin** [QEC-pages/QDistRnd#38]
I am puzzled why your parser prints some errors but then... just proceeds. E.g. this code:
```
                                 q := Int(body);
                                 if IsInt(q) and IsPrimeInt(q) then
                                     return Z(q);
                                 else
                                     Print("\n Argument of ",str,"should be prime\n");
                                 fi;
```
so if `q` is not a prime, it complains and then just proceeds. Why isn't this an `Error`? Similar in a few other places.

**Comment by LeonidPryadko** [comment]
This is a feature to enable more detailed error messages (the logic is set up so that it would give a general error message at the bottom of the function).
