### ISSUE TITLE
Mismatch between the readme and the article

### ISSUE THREAD

**Issue by pan-pavel** [QEC-pages/QDistRnd#4]
The README file says:

> The GAP package QDistRnd implements a probabilistic algorithm for finding the distance of a $q$-ary quantum **low-density parity-check** code 

While the article says:
> The GAP package QDistRnd implements a probabilistic algorithm for finding the minimum distance of a quantum code linear over a finite field GF(q)

I think that the description from the README is much more precise and correct since the implemented algorithm is tailored towards quantum codes with small-weight stabilizers.

**Comment by danielskatz** [comment]
from openjournals/joss-reviews#4120

**Comment by LeonidPryadko** [comment]
Fixed: added the suggested language
