### ISSUE TITLE
Broken release 0.9.5

### ISSUE THREAD

**Issue by fingolfin** [QEC-pages/QDistRnd#46]
It seems you released a new version 0.9.5 of this package. The website is updated but the download link to https://github.com/QEC-pages/QDistRnd/releases/download/v0.9.5/qdistrnd-0.9.5.tar.gz does not work -- indeed 0.9.5 is not listed under https://github.com/QEC-pages/QDistRnd/releases

**Comment by LeonidPryadko** [comment]
It is fixed now (After running the scripts on a ubuntu machine as opposed to WSL under windows).

@fingolfin Apparently ReleaseTools/release-gap-package is broken under Microsoft Windows wsl (ubuntu).  It gives an error message with curl, and this was the reason why the archive and pdf files were not deposited.  I tried upgading GAP (re-compiling latest version from github.com) and also made sure that the ReleaseTools and GitHubPagesForGAP packages are up-to-date.  Here is the error message under WSL:

![image](https://github.com/user-attachments/assets/e92bc27c-9b3f-4b76-a7f7-c5566034d0f1)

```
leonid@upsilon:~/prog/QDistRnd (main=)$ ../ReleaseTools/release-gap-package --no-push
Using PYTHON = '/usr/bin/python'
Using GAP = '/usr/local/bin/gap'
Extracting information from PackageInfo.g...
Package QDistRnd 0.9.5
Building GAP package documentation (using makedoc.g)
Using archive basename qdistrnd-0.9.5
Using GitHub repository QEC-pages/QDistRnd
Using GitHub username QEC-pages
Using branch main
Using git tag v0.9.5 (derived from ArchiveURL in PackageInfo.g)
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
```

**Comment by LeonidPryadko** [comment]
NB: Same error also occurs w/o the `--no-push` argument

**Comment by fingolfin** [comment]
What does `curl --version` say?

**Comment by LeonidPryadko** [comment]
@fingolfin 

```
leonid@upsilon:~/prog/QDistRnd (main=)$ curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

**Comment by fingolfin** [comment]
So that looks essentially sane.

Difficult for me to do anything about this, I don't have access to WSL so I can't do anything to debug this (and frankly I am not very much motivated to debug Windows issues).

My hope for the long term is that we can move away from running ReleaseTools manually on our own computers anyway and instead run something equivalent in GitHub Actions. During last GAP days some initial work on that was done but unfortunately it has stalled since then.

**Comment by fingolfin** [comment]
Unfortunately the release is still broken:
> `tarball contains symlinks: ['qdistrnd-0.9.5/doc/mathjax']`

This is due to the use of Debian's modified (botched?) version of GAPDoc... *sigh*

It may be possible to solve this by either installing GAP manually from source; or by just installing a "clean" GAPDoc and convincing GAP to use that instead of the bundled GAPDoc. Something like this might work:
```
mkdir -p ~/.gap/pkg
cd ~/.gap/pkg
git clone https://github.com/frankluebeck/GAPDoc
```
Then next time you start GAP, its banner should report "GAPDoc 1.6.7.dev" as being loaded.

**Comment by LeonidPryadko** [comment]
@fingolfin 
Thanks for the detailed instructions.  I followed the steps and also verified that the tarball no longer contains symlinks.  This should be resolved now.

**Comment by fingolfin** [comment]
Indeed it works, thank you!
